site_name: Thai Students in Ireland
site_description: Stuff
site_author: Thai Students in Ireland and its Contributors.
site_url: https://thaisocireland.github.io/docs/
repo_url: https://github.com/thaisocireland/docs/
edit_uri: blob/main/docs/
copyright: All content on this website has been <a href="https://creativecommons.org/publicdomain/zero/1.0/ ">marked as dedicated to the public domain.</a> You are free to copy, modify, and redistribute it without attribution. While attribution is not required, we encourage you to link back to the original source.
use_directory_urls: true
theme: material
plugins:
- search
- pdf-export:
    combined: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT  # only export PDF if this is set to 1
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- "หน้าแรก": index.md
- "สุขภาพ": health.md
- "ดับลิน": dublin.md
- "About": README.md
