on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Checkout content
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
        with:
          ref: main
          path: docs
          fetch-depth: 0
      - name: Install pre-requisites for MkDocs
        run: pip install -r docs/requirements.txt
      - name: Set git identity
        working-directory: docs
        run: |
          git config user.name "GitHub Actions [Bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Sync gh-pages
        working-directory: docs
        run: git checkout gh-pages && git pull && git checkout main
      - name: Build docs and set aliases
        working-directory: docs
        run: mkdocs deploy --branch gh-pages --push
